version: "3"
services:
  postgres:
    image: user18081971/2021-erep-postgres:main
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    ports:
      - "15432:5432"

  sol:
    image: user18081971/2021-erep-solr:main
    ports:
      - "8983:8983"

  probing:
    container_name: probing_service
    image: user18081971/probing:deployments
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafk:9092
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8180/auth/realms/quarkus
      QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: http://keycloak:8180/auth/realms/quarkus

    ports:
      - 8080:8080

  crawling:
    container_name: crawling_service
    image: user18081971/crawling:deployments
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafk:9092
      QUARKUS_HTTP_PORT: 8080
    ports:
      - 8080:8080

  scraping:
    container_name: scraping_service
    image: user18081971/scraping:deployments
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafk:9092
      QUARKUS_HTTP_PORT: 8080
      COM_DRAVASSOR_SCRAPING_INDEXING_SOLR_URL: http://sol:8983/solr
    ports:
      - 8080:8080

  scheduling:
    container_name: scheduling_service
    image: user18081971/scheduling:deployments
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafk:9092
      QUARKUS_HTTP_PORT: 8080
    ports:
      - 8080:8080

  searching:
    container_name: searching_service
    image: user18081971/searching:deployments
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafk:9092
      QUARKUS_HTTP_PORT: 8080
      COM_DRAVASSOR_SEARCHING_SOLR_URL: http://sol:8983/solr
    ports:
      - 8080:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafk:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafk:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1