# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pg-pv-volume
#   namespace: n1-user18081998
# spec:
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: manual
#   hostPath:
#     path: /var/lib/pgsql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-volume
  namespace: n1-user18081998
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual