apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: n1-user18081998
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: n1-user18081998
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template: 
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      containers:
      - name: prometheus
        image: user18081971/2021-erep-prometheus:main
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports: 
        - containerPort: 3000
        volumeMounts:
        - name: prometheus-storage
          mountPath: /etc