apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawling-deployment
  namespace: n1-user18081998
  labels:
    app: crawling
spec:
  selector:
    matchLabels:
      app: crawling
  template:
    metadata:
      labels:
        app: crawling
    spec:
      containers:
      - name: crawling
        image: user18081971/crawling:deployments
        ports: 
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-zookeeper:9092"
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: crawling-service
  namespace: n1-user18081998
  labels:
    app: crawling
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: crawling
  type: ClusterIP