apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-deployment
  namespace: n1-user18081998
  labels:
    app: scheduling
spec:
  selector:
    matchLabels:
      app: scheduling
  template:
    metadata:
      labels:
        app: scheduling
    spec:
      containers:
      - name: scheduling
        image: user18081971/scheduling:deployments
        ports: 
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 600Mi
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-zookeeper:9092"
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  namespace: n1-user18081998
  labels:
    app: scheduling
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: scheduling
  type: ClusterIP