# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: zookeeper
#   namespace: n1-user18081998
#   labels:
#     app: zookeeper
# spec:
#   selector:
#     matchLabels:
#       app: zookeeper
#   template:
#     metadata:
#       labels:
#         app: zookeeper
#     spec:
#       containers:
#       - name: zookeeper
#         image: confluentinc/cp-zookeeper:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
  namespace: n1-user18081998
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
          - containerPort: 2181
            name: zookeeper

      - name: kafka-1
        image: "confluentinc/cp-kafka:latest"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-zookeeper:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
  namespace: n1-user18081998
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-zookeeper
  type: ClusterIP