
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: n1-user18081998
  labels:
    app: pg
spec:
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      volumes:
      - name: pg-storage
        persistentVolumeClaim:
          claimName: pg-pvc-volume
      containers:
      - name: postgres
        image: user18081971/2021-erep-postgres:main
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "postgres"
        - name: PGDATA
          value: /data/postgres
        volumeMounts:
        - name: pg-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: n1-user18081998
  labels: 
    app: pg
spec:
  selector:
    app: pg
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
