name: push_dockerfiles_to_registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    #### pg image build ####
      - name: postgres metadata
        id: pg-meta1
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: user18081971/2021-erep-postgres
      - name: pg build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./deployments/dockerfiles/postgres
          push: true
          tags: ${{ steps.pg-meta1.outputs.tags }}
          labels: ${{ steps.pg-meta1.outputs.labels }}

    #### solr image build ####
      - name: solr metadata
        id: solr-meta1
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: user18081971/2021-erep-solr
      - name: solr build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./deployments/dockerfiles/solr
          push: true
          tags: ${{ steps.solr-meta1.outputs.tags }}
          labels: ${{ steps.solr-meta1.outputs.labels }}